# Козлов Даниил
## рабочая тетрадь 2
### задание 1.3.1

In [173]:
import numpy as np

a = np.ones(64).reshape(8,8)
for i in range(8):
    for k in range(8):
        if (i+k)%2 == 1:
            a[i][k]=0;


print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]

### Задача 1.3.2

In [144]:
import numpy as np
a = np.arange(5).reshape(1,5)
a = np.resize(a,(5,5))


print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### задача 1.3.3

In [265]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.67886226 0.44963772 0.95108409]
  [0.0877283  0.71240473 0.54065104]
  [0.25128979 0.97470316 0.19353616]]

 [[0.28560506 0.6021032  0.26471852]
  [0.1381592  0.97525597 0.63309465]
  [0.35440418 0.42869543 0.50965476]]

 [[0.51631796 0.4845096  0.13038188]
  [0.82549534 0.84113451 0.59971405]
  [0.53167681 0.76841976 0.40925445]]]

### задача 1.3.4

In [6]:
import numpy as np
import random
from random import randint
b = random.randint(3,15)
d = random.randint(3,15)
c = d-1;
a = np.array([0])
a = np.resize(a,(b,d))
for i in range(b):
    if i == 0 or i == b-1:
        a[i]=1;
    for k in range(d):
        if k==0 or k == c:
            a[i][k]=1;
print(a)

[[1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1]]

### задача 1.3.5

In [266]:
import numpy as np
a = np.random.random((5,5))
print(np.sort(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### задача 1.3.6

In [11]:
import numpy as np
import random
from random import randint
c = random.randint(1,10)
d = random.randint(1,10)
a = np.array([0])
a = np.resize(a,(c,d))

for i in range(c):
    for k in range(d):
        b = random.randint(0,40)
        a[i][k] = b;
print(a)
print(np.shape(a))
print(a.size)
print(a.ndim)

[[ 3 33  6 30 15 17  2 19 37 18]
 [31 22 23 24 23 21  0  0 19 32]
 [40 12 17  0  0 35 15 33 17 39]
 [12  0 14 39 34  4 22  5 24 19]]
(4, 10)
40
2

### пример 2.2.4

In [28]:
import pandas as pd
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.iloc[4:10]
# dataframe.describe()

,Name,PClass,Age,Sex,Survived,SexCode
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
5,"Anderson, Mr Harry",1st,47.00,male,1,0
6,"Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
7,"Andrews, Mr Thomas, jr",1st,39.00,male,0,0
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1
9,"Artagaveytia, Mr Ramon",1st,71.00,male,0,0

### задача 2.3.1

In [44]:
import pandas as pd
import numpy as np
a = np.array([0,0,0])
b = np.array([2,1,1])
EVK=np.sqrt(np.sum(np.square(a-b)))
print(EVK)

1.7320508075688772

### задача 2.3.2

In [29]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares_1400_more
0,731,12,219,0.663594,1.0,0.815385,4,2,1,0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,0
1,731,9,255,0.604743,1.0,0.791946,3,1,1,0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,0
2,731,9,211,0.575130,1.0,0.663866,3,1,1,0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1
3,731,9,531,0.503788,1.0,0.665635,9,0,1,0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,0
4,731,13,1072,0.415646,1.0,0.540890,19,19,20,0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,0

### задача 2.3.3

In [36]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe.shape

(39644, 60)

In [37]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe.describe()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares_1400_more
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,354.530471,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,0.533599
std,214.163767,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,0.498876
min,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,164.000000,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,0.000000
50%,339.000000,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1.000000
75%,542.000000,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,1.000000
max,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,1.000000

In [38]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe.tail(5)

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares_1400_more
39639,8,11,346,0.529052,1.0,0.684783,9,7,1,1,...,0.100000,0.75,-0.260000,-0.5,-0.125000,0.100000,0.000000,0.400000,0.000000,1
39640,8,12,328,0.696296,1.0,0.885057,9,7,3,48,...,0.136364,0.70,-0.211111,-0.4,-0.100000,0.300000,1.000000,0.200000,1.000000,1
39641,8,10,442,0.516355,1.0,0.644128,24,1,12,1,...,0.136364,0.50,-0.356439,-0.8,-0.166667,0.454545,0.136364,0.045455,0.136364,1
39642,8,6,682,0.539493,1.0,0.692661,10,1,1,0,...,0.062500,0.50,-0.205246,-0.5,-0.012500,0.000000,0.000000,0.500000,0.000000,0
39643,8,10,157,0.701987,1.0,0.846154,1,1,0,2,...,0.100000,0.50,-0.200000,-0.2,-0.200000,0.333333,0.250000,0.166667,0.250000,0

In [40]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe.iloc[5:15]

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares_1400_more
5,731,10,370,0.559889,1.0,0.698198,2,2,0,0,...,0.136364,0.6,-0.195000,-0.4000,-0.100,0.642857,0.214286,0.142857,0.214286,0
6,731,8,960,0.418163,1.0,0.549834,21,20,20,0,...,0.100000,1.0,-0.224479,-0.5000,-0.050,0.000000,0.000000,0.500000,0.000000,0
7,731,12,989,0.433574,1.0,0.572108,20,20,20,0,...,0.100000,1.0,-0.242778,-0.5000,-0.050,1.000000,0.500000,0.500000,0.500000,0
8,731,11,97,0.670103,1.0,0.836735,2,0,0,0,...,0.400000,0.8,-0.125000,-0.1250,-0.125,0.125000,0.000000,0.375000,0.000000,1
9,731,10,231,0.636364,1.0,0.797101,4,1,1,1,...,0.100000,0.5,-0.238095,-0.5000,-0.100,0.000000,0.000000,0.500000,0.000000,0
10,731,9,1248,0.490050,1.0,0.731638,11,0,1,0,...,0.100000,1.0,-0.415064,-1.0000,-0.100,0.000000,0.000000,0.500000,0.000000,1
11,731,10,187,0.666667,1.0,0.800000,7,0,1,0,...,0.200000,0.7,-0.262500,-0.4000,-0.125,0.000000,0.000000,0.500000,0.000000,1
12,731,9,274,0.609195,1.0,0.707602,18,2,11,0,...,0.200000,0.7,-0.310417,-0.6000,-0.050,1.000000,-1.000000,0.500000,1.000000,0
13,731,9,285,0.744186,1.0,0.841530,4,2,0,21,...,0.160000,1.0,-0.337889,-0.7000,-0.100,1.000000,-1.000000,0.500000,1.000000,1
14,731,8,259,0.562753,1.0,0.644444,19,3,9,0,...,0.136364,0.5,-0.138690,-0.1875,-0.050,0.750000,0.550000,0.250000,0.550000,0

In [4]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/online_news_popularity.csv'
dataframe = pd.read_csv(url)
dataframe[dataframe['num_hrefs']== 3].head(3)

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares_1400_more
1,731,9,255,0.604743,1.0,0.791946,3,1,1,0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,0
2,731,9,211,0.575130,1.0,0.663866,3,1,1,0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1
18,731,11,103,0.689320,1.0,0.806452,3,1,1,0,...,0.033333,0.5,-0.125000,-0.125,-0.125000,0.857143,-0.714286,0.357143,0.714286,1

### задание 3.3.2

In [18]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
df.head()


feat_length = np.array(df['sepal_length_cm']) 
feat_width = np.array(df['sepal_width_cm'])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
z_scale = preprocessing.StandardScaler()

scaled_feat_length = minmax_scale.fit_transform(feat_length.reshape(-1, 1))
scaled_feat_width = z_scale.fit_transform(feat_width.reshape(-1, 1))

print(scaled_feat_length[0:5], '\n'*2, scaled_feat_width[0:5])

[[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]]

 [[ 1.03205722]
 [-0.1249576 ]
 [ 0.33784833]
 [ 0.10644536]
 [ 1.26346019]]